// Code generated by go-swagger; DO NOT EDIT.

package tunnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TunnelAddHandlerFunc turns a function with the right signature into a tunnel add handler
type TunnelAddHandlerFunc func(TunnelAddParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TunnelAddHandlerFunc) Handle(params TunnelAddParams) middleware.Responder {
	return fn(params)
}

// TunnelAddHandler interface for that can handle valid tunnel add params
type TunnelAddHandler interface {
	Handle(TunnelAddParams) middleware.Responder
}

// NewTunnelAdd creates a new http.Handler for the tunnel add operation
func NewTunnelAdd(ctx *middleware.Context, handler TunnelAddHandler) *TunnelAdd {
	return &TunnelAdd{Context: ctx, Handler: handler}
}

/*TunnelAdd swagger:route POST /rest/v1/tunnel/{socket} tunnel tunnelAdd

TunAdd adds tunnel to specified network socket

*/
type TunnelAdd struct {
	Context *middleware.Context
	Handler TunnelAddHandler
}

func (o *TunnelAdd) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTunnelAddParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
