// Code generated by go-swagger; DO NOT EDIT.

package tunnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TunnelDeleteHandlerFunc turns a function with the right signature into a tunnel delete handler
type TunnelDeleteHandlerFunc func(TunnelDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TunnelDeleteHandlerFunc) Handle(params TunnelDeleteParams) middleware.Responder {
	return fn(params)
}

// TunnelDeleteHandler interface for that can handle valid tunnel delete params
type TunnelDeleteHandler interface {
	Handle(TunnelDeleteParams) middleware.Responder
}

// NewTunnelDelete creates a new http.Handler for the tunnel delete operation
func NewTunnelDelete(ctx *middleware.Context, handler TunnelDeleteHandler) *TunnelDelete {
	return &TunnelDelete{Context: ctx, Handler: handler}
}

/*TunnelDelete swagger:route DELETE /rest/v1/tunnel/{socket} tunnel tunnelDelete

TunDel removes tunnel entry from list and kills running tunnel process

*/
type TunnelDelete struct {
	Context *middleware.Context
	Handler TunnelDeleteHandler
}

func (o *TunnelDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTunnelDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
