// Code generated by go-swagger; DO NOT EDIT.

package tunnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TunnelDeleteNoContentCode is the HTTP code returned for type TunnelDeleteNoContent
const TunnelDeleteNoContentCode int = 204

/*TunnelDeleteNoContent Deleted

swagger:response tunnelDeleteNoContent
*/
type TunnelDeleteNoContent struct {
}

// NewTunnelDeleteNoContent creates TunnelDeleteNoContent with default headers values
func NewTunnelDeleteNoContent() *TunnelDeleteNoContent {
	return &TunnelDeleteNoContent{}
}

// WriteResponse to the client
func (o *TunnelDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*TunnelDeleteDefault generic error response

swagger:response tunnelDeleteDefault
*/
type TunnelDeleteDefault struct {
	_statusCode int
}

// NewTunnelDeleteDefault creates TunnelDeleteDefault with default headers values
func NewTunnelDeleteDefault(code int) *TunnelDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &TunnelDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the tunnel delete default response
func (o *TunnelDeleteDefault) WithStatusCode(code int) *TunnelDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the tunnel delete default response
func (o *TunnelDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *TunnelDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
