// Code generated by go-swagger; DO NOT EDIT.

package tunnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTunnelDeleteParams creates a new TunnelDeleteParams object
// with the default values initialized.
func NewTunnelDeleteParams() TunnelDeleteParams {
	var ()
	return TunnelDeleteParams{}
}

// TunnelDeleteParams contains all the bound params for the tunnel delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters tunnelDelete
type TunnelDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*PID
	  In: query
	*/
	Pid *string
	/*Socket name
	  Required: true
	  In: path
	*/
	Socket string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *TunnelDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPid, qhkPid, _ := qs.GetOK("pid")
	if err := o.bindPid(qPid, qhkPid, route.Formats); err != nil {
		res = append(res, err)
	}

	rSocket, rhkSocket, _ := route.Params.GetOK("socket")
	if err := o.bindSocket(rSocket, rhkSocket, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TunnelDeleteParams) bindPid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Pid = &raw

	return nil
}

func (o *TunnelDeleteParams) bindSocket(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Socket = raw

	return nil
}
