// Code generated by go-swagger; DO NOT EDIT.

package tunnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewTunnelCheckParams creates a new TunnelCheckParams object
// with the default values initialized.
func NewTunnelCheckParams() TunnelCheckParams {
	var ()
	return TunnelCheckParams{}
}

// TunnelCheckParams contains all the bound params for the tunnel check operation
// typically these are obtained from a http.Request
//
// swagger:parameters tunnelCheck
type TunnelCheckParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *TunnelCheckParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
