// Code generated by go-swagger; DO NOT EDIT.

package vxlan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// VxlanCreateCreatedCode is the HTTP code returned for type VxlanCreateCreated
const VxlanCreateCreatedCode int = 201

/*VxlanCreateCreated Created

swagger:response vxlanCreateCreated
*/
type VxlanCreateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewVxlanCreateCreated creates VxlanCreateCreated with default headers values
func NewVxlanCreateCreated() *VxlanCreateCreated {
	return &VxlanCreateCreated{}
}

// WithPayload adds the payload to the vxlan create created response
func (o *VxlanCreateCreated) WithPayload(payload *models.Message) *VxlanCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the vxlan create created response
func (o *VxlanCreateCreated) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VxlanCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*VxlanCreateDefault generic error response

swagger:response vxlanCreateDefault
*/
type VxlanCreateDefault struct {
	_statusCode int
}

// NewVxlanCreateDefault creates VxlanCreateDefault with default headers values
func NewVxlanCreateDefault(code int) *VxlanCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &VxlanCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the vxlan create default response
func (o *VxlanCreateDefault) WithStatusCode(code int) *VxlanCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the vxlan create default response
func (o *VxlanCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *VxlanCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
