post:
  parameters:
    - name: body
      in: body
      schema:
        $ref: "#/definitions/Configoptions"
  tags:
    - configuration
  operationId: config
  description: "Allows read and write container's configuration file"
  responses:
    200:
      description: OK
      schema:
        $ref: "#/definitions/Message"
    
    default:
      description: error
      schema:
        $ref: "#/definitions/Error"
delete:
  parameters:
    - name: body
      in: body
      schema:
        $ref: "#/definitions/Configoptions"
  tags:
    - config
  operationId: destroyEntry
  description: "Delete entry in configuration file"
  responses:
    204:
      description: Deleted
    default:
      description: error
      schema:
        $ref: "#/definitions/Error"