// Code generated by go-swagger; DO NOT EDIT.

package demote

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// DemoteOKCode is the HTTP code returned for type DemoteOK
const DemoteOKCode int = 200

/*DemoteOK OK

swagger:response demoteOK
*/
type DemoteOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewDemoteOK creates DemoteOK with default headers values
func NewDemoteOK() *DemoteOK {
	return &DemoteOK{}
}

// WithPayload adds the payload to the demote o k response
func (o *DemoteOK) WithPayload(payload *models.Message) *DemoteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the demote o k response
func (o *DemoteOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DemoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DemoteDefault error

swagger:response demoteDefault
*/
type DemoteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDemoteDefault creates DemoteDefault with default headers values
func NewDemoteDefault(code int) *DemoteDefault {
	if code <= 0 {
		code = 500
	}

	return &DemoteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the demote default response
func (o *DemoteDefault) WithStatusCode(code int) *DemoteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the demote default response
func (o *DemoteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the demote default response
func (o *DemoteDefault) WithPayload(payload *models.Error) *DemoteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the demote default response
func (o *DemoteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DemoteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
