// Code generated by go-swagger; DO NOT EDIT.

package resource_host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// RhIDOKCode is the HTTP code returned for type RhIDOK
const RhIDOKCode int = 200

/*RhIDOK JSON formatted Id of RH

swagger:response rhIdOK
*/
type RhIDOK struct {

	/*
	  In: Body
	*/
	Payload models.RhIDOKBody `json:"body,omitempty"`
}

// NewRhIDOK creates RhIDOK with default headers values
func NewRhIDOK() *RhIDOK {
	return &RhIDOK{}
}

// WithPayload adds the payload to the rh Id o k response
func (o *RhIDOK) WithPayload(payload models.RhIDOKBody) *RhIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rh Id o k response
func (o *RhIDOK) SetPayload(payload models.RhIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RhIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.RhIDOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*RhIDDefault generic error response

swagger:response rhIdDefault
*/
type RhIDDefault struct {
	_statusCode int
}

// NewRhIDDefault creates RhIDDefault with default headers values
func NewRhIDDefault(code int) *RhIDDefault {
	if code <= 0 {
		code = 500
	}

	return &RhIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the rh ID default response
func (o *RhIDDefault) WithStatusCode(code int) *RhIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the rh ID default response
func (o *RhIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *RhIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
