// Code generated by go-swagger; DO NOT EDIT.

package cleanup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// CleanupOKCode is the HTTP code returned for type CleanupOK
const CleanupOKCode int = 200

/*CleanupOK OK

swagger:response cleanupOK
*/
type CleanupOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewCleanupOK creates CleanupOK with default headers values
func NewCleanupOK() *CleanupOK {
	return &CleanupOK{}
}

// WithPayload adds the payload to the cleanup o k response
func (o *CleanupOK) WithPayload(payload *models.Message) *CleanupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cleanup o k response
func (o *CleanupOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CleanupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CleanupDefault error

swagger:response cleanupDefault
*/
type CleanupDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCleanupDefault creates CleanupDefault with default headers values
func NewCleanupDefault(code int) *CleanupDefault {
	if code <= 0 {
		code = 500
	}

	return &CleanupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the cleanup default response
func (o *CleanupDefault) WithStatusCode(code int) *CleanupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the cleanup default response
func (o *CleanupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the cleanup default response
func (o *CleanupDefault) WithPayload(payload *models.Error) *CleanupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cleanup default response
func (o *CleanupDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CleanupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
