// Code generated by go-swagger; DO NOT EDIT.

package attach

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AttachHandlerFunc turns a function with the right signature into a attach handler
type AttachHandlerFunc func(AttachParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AttachHandlerFunc) Handle(params AttachParams) middleware.Responder {
	return fn(params)
}

// AttachHandler interface for that can handle valid attach params
type AttachHandler interface {
	Handle(AttachParams) middleware.Responder
}

// NewAttach creates a new http.Handler for the attach operation
func NewAttach(ctx *middleware.Context, handler AttachHandler) *Attach {
	return &Attach{Context: ctx, Handler: handler}
}

/*Attach swagger:route GET /attach/{container} attach attach

LxcAttach allows user to use container's TTY.
`name` should be available running Subutai container, otherwise command will return error message and non-zero exit code.

*/
type Attach struct {
	Context *middleware.Context
	Handler AttachHandler
}

func (o *Attach) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAttachParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
