// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CliListHandlerFunc turns a function with the right signature into a cli list handler
type CliListHandlerFunc func(CliListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CliListHandlerFunc) Handle(params CliListParams) middleware.Responder {
	return fn(params)
}

// CliListHandler interface for that can handle valid cli list params
type CliListHandler interface {
	Handle(CliListParams) middleware.Responder
}

// NewCliList creates a new http.Handler for the cli list operation
func NewCliList(ctx *middleware.Context, handler CliListHandler) *CliList {
	return &CliList{Context: ctx, Handler: handler}
}

/*CliList swagger:route GET /rest/v1/list list cliList

Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc.

*/
type CliList struct {
	Context *middleware.Context
	Handler CliListHandler
}

func (o *CliList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCliListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
