// Code generated by go-swagger; DO NOT EDIT.

package hostname

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// HostnameOKCode is the HTTP code returned for type HostnameOK
const HostnameOKCode int = 200

/*HostnameOK OK

swagger:response hostnameOK
*/
type HostnameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewHostnameOK creates HostnameOK with default headers values
func NewHostnameOK() *HostnameOK {
	return &HostnameOK{}
}

// WithPayload adds the payload to the hostname o k response
func (o *HostnameOK) WithPayload(payload *models.Message) *HostnameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the hostname o k response
func (o *HostnameOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HostnameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*HostnameDefault error

swagger:response hostnameDefault
*/
type HostnameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHostnameDefault creates HostnameDefault with default headers values
func NewHostnameDefault(code int) *HostnameDefault {
	if code <= 0 {
		code = 500
	}

	return &HostnameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the hostname default response
func (o *HostnameDefault) WithStatusCode(code int) *HostnameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the hostname default response
func (o *HostnameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the hostname default response
func (o *HostnameDefault) WithPayload(payload *models.Error) *HostnameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the hostname default response
func (o *HostnameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HostnameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
