/* 
 * Agent API
 *
 * API to handle agent 
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type List struct {

	Text string `json:"text,omitempty"`
}
