// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// BackupContainerOKCode is the HTTP code returned for type BackupContainerOK
const BackupContainerOKCode int = 200

/*BackupContainerOK OK

swagger:response backupContainerOK
*/
type BackupContainerOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewBackupContainerOK creates BackupContainerOK with default headers values
func NewBackupContainerOK() *BackupContainerOK {
	return &BackupContainerOK{}
}

// WithPayload adds the payload to the backup container o k response
func (o *BackupContainerOK) WithPayload(payload *models.Message) *BackupContainerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the backup container o k response
func (o *BackupContainerOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BackupContainerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BackupContainerDefault error

swagger:response backupContainerDefault
*/
type BackupContainerDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBackupContainerDefault creates BackupContainerDefault with default headers values
func NewBackupContainerDefault(code int) *BackupContainerDefault {
	if code <= 0 {
		code = 500
	}

	return &BackupContainerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the backup container default response
func (o *BackupContainerDefault) WithStatusCode(code int) *BackupContainerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the backup container default response
func (o *BackupContainerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the backup container default response
func (o *BackupContainerDefault) WithPayload(payload *models.Error) *BackupContainerDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the backup container default response
func (o *BackupContainerDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BackupContainerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
