// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// BatchOKCode is the HTTP code returned for type BatchOK
const BatchOKCode int = 200

/*BatchOK OK

swagger:response batchOK
*/
type BatchOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewBatchOK creates BatchOK with default headers values
func NewBatchOK() *BatchOK {
	return &BatchOK{}
}

// WithPayload adds the payload to the batch o k response
func (o *BatchOK) WithPayload(payload *models.Message) *BatchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the batch o k response
func (o *BatchOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BatchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BatchDefault error

swagger:response batchDefault
*/
type BatchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBatchDefault creates BatchDefault with default headers values
func NewBatchDefault(code int) *BatchDefault {
	if code <= 0 {
		code = 500
	}

	return &BatchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the batch default response
func (o *BatchDefault) WithStatusCode(code int) *BatchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the batch default response
func (o *BatchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the batch default response
func (o *BatchDefault) WithPayload(payload *models.Error) *BatchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the batch default response
func (o *BatchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BatchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
