// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CliLxcListOKCode is the HTTP code returned for type CliLxcListOK
const CliLxcListOKCode int = 200

/*CliLxcListOK Get all subutai instances

swagger:response cliLxcListOK
*/
type CliLxcListOK struct {
}

// NewCliLxcListOK creates CliLxcListOK with default headers values
func NewCliLxcListOK() *CliLxcListOK {
	return &CliLxcListOK{}
}

// WriteResponse to the client
func (o *CliLxcListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
