// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CliLxcListHandlerFunc turns a function with the right signature into a cli lxc list handler
type CliLxcListHandlerFunc func(CliLxcListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CliLxcListHandlerFunc) Handle(params CliLxcListParams) middleware.Responder {
	return fn(params)
}

// CliLxcListHandler interface for that can handle valid cli lxc list params
type CliLxcListHandler interface {
	Handle(CliLxcListParams) middleware.Responder
}

// NewCliLxcList creates a new http.Handler for the cli lxc list operation
func NewCliLxcList(ctx *middleware.Context, handler CliLxcListHandler) *CliLxcList {
	return &CliLxcList{Context: ctx, Handler: handler}
}

/*CliLxcList swagger:route GET /agent/rest/list cliLxcList

Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc.

*/
type CliLxcList struct {
	Context *middleware.Context
	Handler CliLxcListHandler
}

func (o *CliLxcList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCliLxcListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
