// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// GetContainerInfoOKCode is the HTTP code returned for type GetContainerInfoOK
const GetContainerInfoOKCode int = 200

/*GetContainerInfoOK OK

swagger:response getContainerInfoOK
*/
type GetContainerInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.Container `json:"body,omitempty"`
}

// NewGetContainerInfoOK creates GetContainerInfoOK with default headers values
func NewGetContainerInfoOK() *GetContainerInfoOK {
	return &GetContainerInfoOK{}
}

// WithPayload adds the payload to the get container info o k response
func (o *GetContainerInfoOK) WithPayload(payload *models.Container) *GetContainerInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get container info o k response
func (o *GetContainerInfoOK) SetPayload(payload *models.Container) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContainerInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetContainerInfoDefault error

swagger:response getContainerInfoDefault
*/
type GetContainerInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetContainerInfoDefault creates GetContainerInfoDefault with default headers values
func NewGetContainerInfoDefault(code int) *GetContainerInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetContainerInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get container info default response
func (o *GetContainerInfoDefault) WithStatusCode(code int) *GetContainerInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get container info default response
func (o *GetContainerInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get container info default response
func (o *GetContainerInfoDefault) WithPayload(payload *models.Error) *GetContainerInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get container info default response
func (o *GetContainerInfoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContainerInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
