// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ImportHandlerFunc turns a function with the right signature into a import handler
type ImportHandlerFunc func(ImportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ImportHandlerFunc) Handle(params ImportParams) middleware.Responder {
	return fn(params)
}

// ImportHandler interface for that can handle valid import params
type ImportHandler interface {
	Handle(ImportParams) middleware.Responder
}

// NewImport creates a new http.Handler for the import operation
func NewImport(ctx *middleware.Context, handler ImportHandler) *Import {
	return &Import{Context: ctx, Handler: handler}
}

/*Import swagger:route GET /rest/v1/import/{container} agent cli list import

Import Subutai template

*/
type Import struct {
	Context *middleware.Context
	Handler ImportHandler
}

func (o *Import) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewImportParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
