// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// MetricsOKCode is the HTTP code returned for type MetricsOK
const MetricsOKCode int = 200

/*MetricsOK Ok

swagger:response metricsOK
*/
type MetricsOK struct {

	/*
	  In: Body
	*/
	Payload models.MetricsOKBody `json:"body,omitempty"`
}

// NewMetricsOK creates MetricsOK with default headers values
func NewMetricsOK() *MetricsOK {
	return &MetricsOK{}
}

// WithPayload adds the payload to the metrics o k response
func (o *MetricsOK) WithPayload(payload models.MetricsOKBody) *MetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the metrics o k response
func (o *MetricsOK) SetPayload(payload models.MetricsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.MetricsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*MetricsDefault generic error response

swagger:response metricsDefault
*/
type MetricsDefault struct {
	_statusCode int
}

// NewMetricsDefault creates MetricsDefault with default headers values
func NewMetricsDefault(code int) *MetricsDefault {
	if code <= 0 {
		code = 500
	}

	return &MetricsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the metrics default response
func (o *MetricsDefault) WithStatusCode(code int) *MetricsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the metrics default response
func (o *MetricsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *MetricsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
