// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// P2pListOKCode is the HTTP code returned for type P2pListOK
const P2pListOKCode int = 200

/*P2pListOK Ok

swagger:response p2pListOK
*/
type P2pListOK struct {

	/*
	  In: Body
	*/
	Payload models.P2pListOKBody `json:"body,omitempty"`
}

// NewP2pListOK creates P2pListOK with default headers values
func NewP2pListOK() *P2pListOK {
	return &P2pListOK{}
}

// WithPayload adds the payload to the p2p list o k response
func (o *P2pListOK) WithPayload(payload models.P2pListOKBody) *P2pListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p2p list o k response
func (o *P2pListOK) SetPayload(payload models.P2pListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *P2pListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.P2pListOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*P2pListDefault generic error response

swagger:response p2pListDefault
*/
type P2pListDefault struct {
	_statusCode int
}

// NewP2pListDefault creates P2pListDefault with default headers values
func NewP2pListDefault(code int) *P2pListDefault {
	if code <= 0 {
		code = 500
	}

	return &P2pListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the p2p list default response
func (o *P2pListDefault) WithStatusCode(code int) *P2pListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the p2p list default response
func (o *P2pListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *P2pListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
