// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// PromoteOKCode is the HTTP code returned for type PromoteOK
const PromoteOKCode int = 200

/*PromoteOK OK

swagger:response promoteOK
*/
type PromoteOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewPromoteOK creates PromoteOK with default headers values
func NewPromoteOK() *PromoteOK {
	return &PromoteOK{}
}

// WithPayload adds the payload to the promote o k response
func (o *PromoteOK) WithPayload(payload *models.Message) *PromoteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the promote o k response
func (o *PromoteOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PromoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PromoteDefault error

swagger:response promoteDefault
*/
type PromoteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPromoteDefault creates PromoteDefault with default headers values
func NewPromoteDefault(code int) *PromoteDefault {
	if code <= 0 {
		code = 500
	}

	return &PromoteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the promote default response
func (o *PromoteDefault) WithStatusCode(code int) *PromoteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the promote default response
func (o *PromoteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the promote default response
func (o *PromoteDefault) WithPayload(payload *models.Error) *PromoteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the promote default response
func (o *PromoteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PromoteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
