// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// ProxyCreateCreatedCode is the HTTP code returned for type ProxyCreateCreated
const ProxyCreateCreatedCode int = 201

/*ProxyCreateCreated Created

swagger:response proxyCreateCreated
*/
type ProxyCreateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewProxyCreateCreated creates ProxyCreateCreated with default headers values
func NewProxyCreateCreated() *ProxyCreateCreated {
	return &ProxyCreateCreated{}
}

// WithPayload adds the payload to the proxy create created response
func (o *ProxyCreateCreated) WithPayload(payload *models.Message) *ProxyCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the proxy create created response
func (o *ProxyCreateCreated) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProxyCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ProxyCreateDefault generic error response

swagger:response proxyCreateDefault
*/
type ProxyCreateDefault struct {
	_statusCode int
}

// NewProxyCreateDefault creates ProxyCreateDefault with default headers values
func NewProxyCreateDefault(code int) *ProxyCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &ProxyCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the proxy create default response
func (o *ProxyCreateDefault) WithStatusCode(code int) *ProxyCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the proxy create default response
func (o *ProxyCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *ProxyCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
