// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// RestoreOKCode is the HTTP code returned for type RestoreOK
const RestoreOKCode int = 200

/*RestoreOK Ok

swagger:response restoreOK
*/
type RestoreOK struct {

	/*
	  In: Body
	*/
	Payload models.RestoreOKBody `json:"body,omitempty"`
}

// NewRestoreOK creates RestoreOK with default headers values
func NewRestoreOK() *RestoreOK {
	return &RestoreOK{}
}

// WithPayload adds the payload to the restore o k response
func (o *RestoreOK) WithPayload(payload models.RestoreOKBody) *RestoreOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the restore o k response
func (o *RestoreOK) SetPayload(payload models.RestoreOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestoreOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.RestoreOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*RestoreDefault generic error response

swagger:response restoreDefault
*/
type RestoreDefault struct {
	_statusCode int
}

// NewRestoreDefault creates RestoreDefault with default headers values
func NewRestoreDefault(code int) *RestoreDefault {
	if code <= 0 {
		code = 500
	}

	return &RestoreDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the restore default response
func (o *RestoreDefault) WithStatusCode(code int) *RestoreDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the restore default response
func (o *RestoreDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *RestoreDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
