// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// StopOKCode is the HTTP code returned for type StopOK
const StopOKCode int = 200

/*StopOK Ok

swagger:response stopOK
*/
type StopOK struct {

	/*
	  In: Body
	*/
	Payload models.StopOKBody `json:"body,omitempty"`
}

// NewStopOK creates StopOK with default headers values
func NewStopOK() *StopOK {
	return &StopOK{}
}

// WithPayload adds the payload to the stop o k response
func (o *StopOK) WithPayload(payload models.StopOKBody) *StopOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop o k response
func (o *StopOK) SetPayload(payload models.StopOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.StopOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*StopDefault generic error response

swagger:response stopDefault
*/
type StopDefault struct {
	_statusCode int
}

// NewStopDefault creates StopDefault with default headers values
func NewStopDefault(code int) *StopDefault {
	if code <= 0 {
		code = 500
	}

	return &StopDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the stop default response
func (o *StopDefault) WithStatusCode(code int) *StopDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the stop default response
func (o *StopDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *StopDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
