// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// VxlanDeleteHandlerFunc turns a function with the right signature into a vxlan delete handler
type VxlanDeleteHandlerFunc func(VxlanDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VxlanDeleteHandlerFunc) Handle(params VxlanDeleteParams) middleware.Responder {
	return fn(params)
}

// VxlanDeleteHandler interface for that can handle valid vxlan delete params
type VxlanDeleteHandler interface {
	Handle(VxlanDeleteParams) middleware.Responder
}

// NewVxlanDelete creates a new http.Handler for the vxlan delete operation
func NewVxlanDelete(ctx *middleware.Context, handler VxlanDeleteHandler) *VxlanDelete {
	return &VxlanDelete{Context: ctx, Handler: handler}
}

/*VxlanDelete swagger:route DELETE /rest/v1/vxlan/{iface} agent cli list vxlanDelete

removes OVS bridges and ports by name, brings system interface down

*/
type VxlanDelete struct {
	Context *middleware.Context
	Handler VxlanDeleteHandler
}

func (o *VxlanDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVxlanDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
