// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// VxlanListOKCode is the HTTP code returned for type VxlanListOK
const VxlanListOKCode int = 200

/*VxlanListOK Ok

swagger:response vxlanListOK
*/
type VxlanListOK struct {

	/*
	  In: Body
	*/
	Payload models.VxlanListOKBody `json:"body,omitempty"`
}

// NewVxlanListOK creates VxlanListOK with default headers values
func NewVxlanListOK() *VxlanListOK {
	return &VxlanListOK{}
}

// WithPayload adds the payload to the vxlan list o k response
func (o *VxlanListOK) WithPayload(payload models.VxlanListOKBody) *VxlanListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the vxlan list o k response
func (o *VxlanListOK) SetPayload(payload models.VxlanListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VxlanListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.VxlanListOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*VxlanListDefault generic error response

swagger:response vxlanListDefault
*/
type VxlanListDefault struct {
	_statusCode int
}

// NewVxlanListDefault creates VxlanListDefault with default headers values
func NewVxlanListDefault(code int) *VxlanListDefault {
	if code <= 0 {
		code = 500
	}

	return &VxlanListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the vxlan list default response
func (o *VxlanListDefault) WithStatusCode(code int) *VxlanListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the vxlan list default response
func (o *VxlanListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *VxlanListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
