// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VxlanDeleteNoContentCode is the HTTP code returned for type VxlanDeleteNoContent
const VxlanDeleteNoContentCode int = 204

/*VxlanDeleteNoContent Deleted

swagger:response vxlanDeleteNoContent
*/
type VxlanDeleteNoContent struct {
}

// NewVxlanDeleteNoContent creates VxlanDeleteNoContent with default headers values
func NewVxlanDeleteNoContent() *VxlanDeleteNoContent {
	return &VxlanDeleteNoContent{}
}

// WriteResponse to the client
func (o *VxlanDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*VxlanDeleteDefault generic error response

swagger:response vxlanDeleteDefault
*/
type VxlanDeleteDefault struct {
	_statusCode int
}

// NewVxlanDeleteDefault creates VxlanDeleteDefault with default headers values
func NewVxlanDeleteDefault(code int) *VxlanDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &VxlanDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the vxlan delete default response
func (o *VxlanDeleteDefault) WithStatusCode(code int) *VxlanDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the vxlan delete default response
func (o *VxlanDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *VxlanDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
