// Code generated by go-swagger; DO NOT EDIT.

package restore

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRestoreParams creates a new RestoreParams object
// with the default values initialized.
func NewRestoreParams() RestoreParams {
	var ()
	return RestoreParams{}
}

// RestoreParams contains all the bound params for the restore operation
// typically these are obtained from a http.Request
//
// swagger:parameters restore
type RestoreParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Container name
	  Required: true
	  In: path
	*/
	Container string
	/*Date argument
	  In: query
	*/
	Date *string
	/*Name of new container
	  In: query
	*/
	Newcontainer *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *RestoreParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rContainer, rhkContainer, _ := route.Params.GetOK("container")
	if err := o.bindContainer(rContainer, rhkContainer, route.Formats); err != nil {
		res = append(res, err)
	}

	qDate, qhkDate, _ := qs.GetOK("date")
	if err := o.bindDate(qDate, qhkDate, route.Formats); err != nil {
		res = append(res, err)
	}

	qNewcontainer, qhkNewcontainer, _ := qs.GetOK("newcontainer")
	if err := o.bindNewcontainer(qNewcontainer, qhkNewcontainer, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestoreParams) bindContainer(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Container = raw

	return nil
}

func (o *RestoreParams) bindDate(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Date = &raw

	return nil
}

func (o *RestoreParams) bindNewcontainer(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Newcontainer = &raw

	return nil
}
