// Code generated by go-swagger; DO NOT EDIT.

package p2p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// P2pDeleteNoContentCode is the HTTP code returned for type P2pDeleteNoContent
const P2pDeleteNoContentCode int = 204

/*P2pDeleteNoContent Deleted

swagger:response p2pDeleteNoContent
*/
type P2pDeleteNoContent struct {
}

// NewP2pDeleteNoContent creates P2pDeleteNoContent with default headers values
func NewP2pDeleteNoContent() *P2pDeleteNoContent {
	return &P2pDeleteNoContent{}
}

// WriteResponse to the client
func (o *P2pDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*P2pDeleteDefault generic error response

swagger:response p2pDeleteDefault
*/
type P2pDeleteDefault struct {
	_statusCode int
}

// NewP2pDeleteDefault creates P2pDeleteDefault with default headers values
func NewP2pDeleteDefault(code int) *P2pDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &P2pDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the p2p delete default response
func (o *P2pDeleteDefault) WithStatusCode(code int) *P2pDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the p2p delete default response
func (o *P2pDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *P2pDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
