// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DestroyOneURL generates an URL for the destroy one operation
type DestroyOneURL struct {
	Name string

	ContainersOnly *bool
	DetailedInfo   *bool
	TemplatesOnly  *bool
	WithAncestors  *bool
	WithParents    *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DestroyOneURL) WithBasePath(bp string) *DestroyOneURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DestroyOneURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DestroyOneURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/rest/v1/container/{name}"

	name := o.Name
	if name != "" {
		_path = strings.Replace(_path, "{name}", name, -1)
	} else {
		return nil, errors.New("Name is required on DestroyOneURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var containersOnly string
	if o.ContainersOnly != nil {
		containersOnly = swag.FormatBool(*o.ContainersOnly)
	}
	if containersOnly != "" {
		qs.Set("containersOnly", containersOnly)
	}

	var detailedInfo string
	if o.DetailedInfo != nil {
		detailedInfo = swag.FormatBool(*o.DetailedInfo)
	}
	if detailedInfo != "" {
		qs.Set("detailedInfo", detailedInfo)
	}

	var templatesOnly string
	if o.TemplatesOnly != nil {
		templatesOnly = swag.FormatBool(*o.TemplatesOnly)
	}
	if templatesOnly != "" {
		qs.Set("templatesOnly", templatesOnly)
	}

	var withAncestors string
	if o.WithAncestors != nil {
		withAncestors = swag.FormatBool(*o.WithAncestors)
	}
	if withAncestors != "" {
		qs.Set("withAncestors", withAncestors)
	}

	var withParents string
	if o.WithParents != nil {
		withParents = swag.FormatBool(*o.WithParents)
	}
	if withParents != "" {
		qs.Set("withParents", withParents)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DestroyOneURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DestroyOneURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DestroyOneURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DestroyOneURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DestroyOneURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DestroyOneURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
