// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Agent API
API to handle agent



    Schemes:
      http
      https
    Host: localhost:8080
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
