// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Hub API
Subutai Agent private REST API


    Schemes:
      http
    Host: hub.subut.ai
    BasePath: /rest/v1/agent
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
