// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Agent API
API to handle agent


    Schemes:
      http
    Host: hub.subut.ai
    BasePath: /rest/v1/agent
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
