// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API to handle agent",
    "title": "Agent API",
    "version": "0.0.1"
  },
  "host": "hub.subut.ai",
  "basePath": "/rest/v1/agent",
  "paths": {
    "/attach/{container}": {
      "get": {
        "description": "LxcAttach allows user to use container's TTY.\n` + "`" + `name` + "`" + ` should be available running Subutai container, otherwise command will return error message and non-zero exit code.",
        "tags": [
          "attach"
        ],
        "operationId": "attach",
        "parameters": [
          {
            "type": "string",
            "description": "Container to be attached",
            "name": "container",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/backup/{name}": {
      "get": {
        "description": "BackupContainer takes a snapshots of each container's volume and stores it in the ` + "`" + `/mnt/backups/container_name/datetime/` + "`" + ` directory. A full backup creates a delta-file of each BTRFS subvolume. An incremental backup (default) creates a delta-file with the difference of changes between the current and last snapshots. All deltas are compressed to archives in ` + "`" + `/mnt/backups/` + "`" + ` directory (container_datetime.tar.gz or container_datetime_Full.tar.gz for full backup). A changelog file can be found next to backups archive (container_datetime_changelog.txt or container_datetime_Full_changelog.txt) which contains a list of changes made between two backups.",
        "tags": [
          "backup"
        ],
        "operationId": "backupContainer",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "name",
          "in": "path",
          "required": true
        },
        {
          "type": "boolean",
          "name": "full",
          "in": "query"
        },
        {
          "type": "boolean",
          "name": "stop",
          "in": "query"
        }
      ]
    },
    "/batch": {
      "post": {
        "description": "Batch binding provides a mechanism to perform several Subutai commands in the container in batch, passed in a single JSON message. Initially, the purpose of this command was internal for SS \u003c-\u003e Agent communication, yet it may be invoked manually from the CLI. The response from a batch command returns a JSON array with each element representing the results (response) from each command (request) in the batch: the positions of responses correlate with the request position in the array",
        "tags": [
          "batch"
        ],
        "operationId": "batch",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Batchline"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/cleanup": {
      "get": {
        "description": "Cleanup simply removes every resource associated with a Subutai container or template: data, network, configs, etc. The destroy command always runs each step in \"force\" mode to provide reliable deletion results; even if some instance components were already removed, the destroy command will continue to perform all operations once again while ignoring possible underlying errors: i.e. missing configuration files.",
        "tags": [
          "cleanup"
        ],
        "operationId": "cleanup",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/clone/{parent}/{child}": {
      "post": {
        "description": "Clone function creates new ` + "`" + `child` + "`" + ` container from a Subutai ` + "`" + `parent` + "`" + ` template. If the specified template argument is not deployed in system, Subutai first tries to import it, and if import succeeds, it then continues to clone from the imported template image. By default, clone will use the NAT-ed network interface with IP address received from the Subutai DHCP server, but this behavior can be changed with command options described below.\nIf ` + "`" + `ipaddr` + "`" + ` option is defined, separate bridge interface will be created in specified VLAN and new container will receive static IP address. Option ` + "`" + `envID` + "`" + ` writes the environment ID string inside new container. Option ` + "`" + `token` + "`" + ` is intended to check the origin of new container creation request during environment build. This is one of the security checks which makes sure that each container creation request is authorized by registered user.\nOption ` + "`" + `kurjunToken` + "`" + ` set kurjun token to clone private and shared templates\nThe clone options are not intended for manual use: unless you're confident about what you're doing. Use default clone format without additional options to create Subutai containers.",
        "tags": [
          "clone"
        ],
        "operationId": "clone",
        "parameters": [
          {
            "type": "string",
            "description": "Parent name",
            "name": "parent",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Child name",
            "name": "child",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Cloneargs"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/config": {
      "post": {
        "description": "Allows read and write container's configuration file",
        "tags": [
          "configuration"
        ],
        "operationId": "config",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Configoptions"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete entry in configuration file",
        "tags": [
          "config"
        ],
        "operationId": "destroyEntry",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Configoptions"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/container/{name}": {
      "get": {
        "description": "Get container Info in JSON formatted object",
        "tags": [
          "container"
        ],
        "operationId": "getContainerInfo",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Container"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "container"
        ],
        "operationId": "destroyOne",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Name of container",
          "name": "name",
          "in": "path",
          "required": true
        },
        {
          "type": "boolean",
          "description": "Parameter to return containers only",
          "name": "containersOnly",
          "in": "query"
        },
        {
          "type": "boolean",
          "description": "Parameter to return templates only",
          "name": "templatesOnly",
          "in": "query"
        },
        {
          "type": "boolean",
          "description": "Parameter to return containers/templates with ancestors",
          "name": "withAncestors",
          "in": "query"
        },
        {
          "type": "boolean",
          "description": "Parameter to return containers/templates with parents",
          "name": "withParents",
          "in": "query"
        },
        {
          "type": "boolean",
          "description": "Parameter to return detailed info",
          "name": "detailedInfo",
          "in": "query"
        }
      ]
    },
    "/demote/{container}": {
      "post": {
        "description": "Converts template into regular Subutai container.\nA Subutai template is a \"locked down\" container only to be used for cloning purposes. It cannot be started, and its file system cannot be modified: it's read-only. Normal operational containers are promoted into templates, but sometimes you might want to demote them back to regular containers. This is what the demote sub command does: it reverts a template without children back into a normal container. Demoted container will use NAT network interface and dynamic IP address if opposite options are not specified.",
        "tags": [
          "demote"
        ],
        "operationId": "demote",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Demoteoptions"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/destroy/{ID}": {
      "get": {
        "description": "Destroy Subutai container",
        "tags": [
          "destroy"
        ],
        "operationId": "destroy",
        "parameters": [
          {
            "type": "string",
            "description": "container name or vlan id",
            "name": "ID",
            "in": "path",
            "required": true
          },
          {
            "type": "boolean",
            "description": "If true the ID is a vlan, if false is a container name",
            "name": "vlan",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/export/{container}": {
      "post": {
        "description": "Export prepares an archive from a template in the ` + "`" + `/mnt/lib/lxc/tmpdir/` + "`" + ` path. This archive can be moved to another Subutai peer and deployed as ready-to-use template or uploaded to Subutai's global template repository to make it widely available for others to use.\nExport consist of two steps if the target is a container: container promotion to template (see \"promote\" command) and packing the template into the archive. If already a template just the packing of the archive takes place.\nConfiguration values for template metadata parameters can be overridden on export, like the recommended container size when the template is cloned using ` + "`" + `-s` + "`" + ` option.",
        "tags": [
          "export"
        ],
        "operationId": "export",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Exportoptions"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/hostname/{container}/{name}": {
      "post": {
        "description": "        - type: string name: container in: path required: true",
        "tags": [
          "hostname"
        ],
        "operationId": "hostname",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "New name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/import/{container}": {
      "get": {
        "description": "Import Subutai template",
        "tags": [
          "import"
        ],
        "operationId": "import",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Importoptions"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/info": {
      "get": {
        "description": "Info command's purposed is to display common system information, such as external IP address to access the container host quotas, its CPU model, RAM size, etc. It's mainly used for internal SS needs.",
        "tags": [
          "info"
        ],
        "operationId": "info",
        "parameters": [
          {
            "type": "string",
            "description": "Commands available:  ipaddr, ports, os, quota, system",
            "name": "command",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/InfoHostStat"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/list": {
      "get": {
        "description": "Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc.",
        "tags": [
          "list"
        ],
        "operationId": "cliList",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "description": "Limit of returned entries on response",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "boolean",
            "description": "Parameter to return containers only",
            "name": "containersOnly",
            "in": "query"
          },
          {
            "type": "boolean",
            "description": "Parameter to return templates only",
            "name": "templatesOnly",
            "in": "query"
          },
          {
            "type": "boolean",
            "description": "Parameter to return containers/templates with ancestors",
            "name": "withAncestors",
            "in": "query"
          },
          {
            "type": "boolean",
            "description": "Parameter to return containers/templates with parents",
            "name": "withParents",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List all subutai instances",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Container"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/metrics": {
      "get": {
        "description": "HostMetrics function retrieves monitoring data from a time-series database deployed in the SS Management server for container hosts and Resource Hosts. Statistics are being collected by the Subutai daemon and includes common information like CPU utilization, network load, RAM and disk usage for both containers and hosts. Since the database is located on the SS Management Host, hosts which are not a part of a Subutai peer have no access to this information. Data aggregation in the time-series database has following configuration: last hour statistic is stored \"as is\", last day data aggregates to 1 minute interval, last week is in 5 minute intervals, After 7 days all statistics is are overwritten by new incoming data.",
        "tags": [
          "metrics"
        ],
        "operationId": "metrics",
        "parameters": [
          {
            "type": "string",
            "description": "Start date. Date Example: 2006-01-02 15:04:05",
            "name": "start",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "End date.  Date Example: 2006-01-02 15:04:05",
            "name": "end",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/MetricInfo"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/p2p": {
      "get": {
        "description": "P2P function controls and configures the peer-to-peer network structure: the swarm which includes all hosts with same the same swarm hash and secret key.\nP2P is a base layer for Subutai environment networking: all containers in same environment are connected to each other via VXLAN tunnels and are accesses as if they were in one LAN. It doesn't matter where the containers are physically located.",
        "tags": [
          "p2p"
        ],
        "operationId": "p2pList",
        "parameters": [
          {
            "type": "string",
            "description": "Accepted commands: - list: list of p2p instances - interfaces: list of p2p interfaces - peers: list of p2p swarm participants by hash - version: print p2p version",
            "name": "command",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Text"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      },
      "put": {
        "description": "P2P function controls and configures the peer-to-peer network structure: the swarm which includes all hosts with same the same swarm hash and secret key.\nP2P is a base layer for Subutai environment networking: all containers in same environment are connected to each other via VXLAN tunnels and are accesses as if they were in one LAN. It doesn't matter where the containers are physically located.",
        "tags": [
          "p2p"
        ],
        "operationId": "p2pUpdate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/P2pArgs"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Text"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      },
      "post": {
        "description": "P2P function controls and configures the peer-to-peer network structure: the swarm which includes all hosts with same the same swarm hash and secret key.\nP2P is a base layer for Subutai environment networking: all containers in same environment are connected to each other via VXLAN tunnels and are accesses as if they were in one LAN. It doesn't matter where the containers are physically located.",
        "tags": [
          "p2p"
        ],
        "operationId": "p2pCreate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/P2pArgs"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Item"
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      },
      "delete": {
        "description": "P2P function controls and configures the peer-to-peer network structure: the swarm which includes all hosts with same the same swarm hash and secret key.\nP2P is a base layer for Subutai environment networking: all containers in same environment are connected to each other via VXLAN tunnels and are accesses as if they were in one LAN. It doesn't matter where the containers are physically located.",
        "tags": [
          "p2p"
        ],
        "operationId": "p2pDelete",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/P2pArgs"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/promote/{container}": {
      "post": {
        "description": "Promote turns a Subutai container into container template which may be cloned with \"clone\" command. Promote executes several simple steps, such as dropping a container's configuration to default values, dumping the list of installed packages (this step requires the target container to still be running), and setting the container's filesystem to read-only to prevent changes.",
        "tags": [
          "promote"
        ],
        "operationId": "promote",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Promoteoptions"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/proxy": {
      "get": {
        "description": "ProxyCheck exits with 0 code if domain or node is exists in specified vlan, otherwise exitcode is 1",
        "tags": [
          "proxy"
        ],
        "operationId": "proxyCheck",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/ProxyArgs"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      },
      "post": {
        "description": "ProxyAdd checks input args and perform required operations to configure reverse proxy",
        "tags": [
          "proxy"
        ],
        "operationId": "proxyCreate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/ProxyArgs"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      },
      "delete": {
        "description": "ProxyDel checks what need to be removed - domain or node and pass args to required functions",
        "tags": [
          "proxy"
        ],
        "operationId": "proxyDelete",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/ProxyArgs"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/quota": {
      "get": {
        "description": "Quota function controls container's quotas and thresholds. Available resources: cpu, % cpuset, available cores ram, Mb network, Kbps rootfs/home/var/opt, Gb The threshold value represents a percentage for each resource. Once resource consumption exceeds this threshold it triggers an alert. The clone operation, sets no quotas and thresholds for new containers; quotas need to be configured with quota command after a clone operation.",
        "tags": [
          "quota"
        ],
        "operationId": "quota",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/quotaArgs"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/quotaOutput"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/rename/{source}/{newname}": {
      "get": {
        "description": "Renames a Subutai container impacting filesystem paths, configuration values, etc.",
        "tags": [
          "rename"
        ],
        "operationId": "rename",
        "parameters": [
          {
            "type": "string",
            "description": "Source name",
            "name": "source",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "New name",
            "name": "newname",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/restore/{container}": {
      "get": {
        "description": "RestoreContainer restores a Subutai container to a snapshot at a specified timestamp if such a backup archive is available.",
        "tags": [
          "restore"
        ],
        "operationId": "restore",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Date argument",
            "name": "date",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Name of new container",
            "name": "newcontainer",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/rh/id": {
      "get": {
        "description": "Returns JSON formatted Id of RH, UUID which is the PGP fingerprint",
        "tags": [
          "resource host"
        ],
        "operationId": "rhID",
        "responses": {
          "200": {
            "description": "JSON formatted Id of RH",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Fingerprint"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/start/{container}": {
      "get": {
        "description": "Starts a Subutai container and checks if container state changed to \"running\" or \"starting\". If state is not changing for 60 seconds, then the \"start\" operation is considered to have failed.",
        "tags": [
          "start"
        ],
        "operationId": "start",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/stop/{container}": {
      "get": {
        "description": "Stops a Subutai container with an additional state check.",
        "tags": [
          "stop"
        ],
        "operationId": "stop",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/tunnel/check": {
      "get": {
        "description": "reads list, checks tunnel ttl, its state and then adds or removes required tunnels",
        "tags": [
          "tunnel"
        ],
        "operationId": "tunnelCheck",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Item"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/tunnel/list": {
      "get": {
        "description": "performs tunnel check and shows \"alive\" tunnels",
        "tags": [
          "tunnel"
        ],
        "operationId": "tunnelList",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Item"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/tunnel/{socket}": {
      "post": {
        "description": "TunAdd adds tunnel to specified network socket",
        "tags": [
          "tunnel"
        ],
        "operationId": "tunnelAdd",
        "parameters": [
          {
            "type": "string",
            "description": "Socket name",
            "name": "socket",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Tunnels may also be set to be permanent (default) or temporary (ttl in seconds). The default destination port is 22.",
            "name": "timeout",
            "in": "query"
          },
          {
            "type": "boolean",
            "description": "There are two types of channels - local (default), which is created from destination address to host and global, from destination to Subutai Helper node.",
            "name": "global",
            "in": "query"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      },
      "delete": {
        "description": "TunDel removes tunnel entry from list and kills running tunnel process",
        "tags": [
          "tunnel"
        ],
        "operationId": "tunnelDelete",
        "parameters": [
          {
            "type": "string",
            "description": "Socket name",
            "name": "socket",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "PID",
            "name": "pid",
            "in": "query"
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/update/{container}": {
      "get": {
        "description": "Update operation can be divided into two different types: container updates and Resource Host updates. Container updates simply perform apt-get update and upgrade operations inside target containers without any extra commands. Since SS Management is just another container, the Subutai update command works fine with the management container too.\nThe second type of update, a Resource Host update, checks the Ubuntu Store and compares available snap packages with those currently installed in the system and, if a newer version is found, installs it. Please note, system security policies requires that such commands should be performed by the superuser manually, otherwise an application's attempt to update itself will be blocked.",
        "tags": [
          "update"
        ],
        "operationId": "update",
        "parameters": [
          {
            "type": "string",
            "description": "Container name",
            "name": "container",
            "in": "path",
            "required": true
          },
          {
            "type": "boolean",
            "description": "Just check for updates, don't update",
            "name": "check",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/vxlan/list": {
      "get": {
        "description": "prints a list of existing VXLAN tunnels",
        "tags": [
          "vxlan"
        ],
        "operationId": "vxlanList",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Item"
              }
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/vxlan/{iface}": {
      "delete": {
        "description": "removes OVS bridges and ports by name, brings system interface down",
        "tags": [
          "vxlan"
        ],
        "operationId": "vxlanDelete",
        "parameters": [
          {
            "type": "string",
            "description": "Network interface name",
            "name": "iface",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    },
    "/vxlan/{tunnel}": {
      "post": {
        "description": "Creates VXLAN tunnel",
        "tags": [
          "vxlan"
        ],
        "operationId": "vxlanCreate",
        "parameters": [
          {
            "type": "string",
            "description": "Tunnel name",
            "name": "tunnel",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Remote IP",
            "name": "remoteip",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Virtual local network",
            "name": "vlan",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Virtual Network Interface",
            "name": "vni",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "default": {
            "description": "generic error response"
          }
        },
        "x-swagger-router-controller": "Default"
      }
    }
  },
  "definitions": {
    "Batchline": {
      "type": "object",
      "required": [
        "action",
        "args"
      ],
      "properties": {
        "action": {
          "description": "Action to be executed list, backup, import, promote etc.",
          "type": "string",
          "readOnly": true
        },
        "args": {
          "description": "Arguments to action command",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Item"
          },
          "readOnly": true
        }
      }
    },
    "Cloneargs": {
      "type": "object",
      "required": [
        "parent",
        "child"
      ],
      "properties": {
        "child": {
          "description": "Child name",
          "type": "string",
          "readOnly": true
        },
        "envID": {
          "description": "Environment ID",
          "type": "string",
          "readOnly": true
        },
        "ipaddr": {
          "description": "IP address",
          "type": "string",
          "readOnly": true
        },
        "kurjunToken": {
          "description": "Kurjun Token",
          "type": "string",
          "readOnly": true
        },
        "parent": {
          "description": "Container/Template parent name",
          "type": "string",
          "readOnly": true
        },
        "token": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Configoptions": {
      "description": "Key / Value pair configuration",
      "type": "object",
      "required": [
        "key",
        "value"
      ],
      "properties": {
        "key": {
          "description": "Key",
          "type": "string",
          "readOnly": true
        },
        "value": {
          "description": "Value",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Container": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "ancestor": {
          "description": "Name of container's ancestor",
          "type": "string",
          "minLength": 1
        },
        "name": {
          "description": "Name of container",
          "type": "string",
          "readOnly": true
        },
        "parent": {
          "description": "Name of container's parent",
          "type": "string",
          "minLength": 1
        }
      }
    },
    "Demoteoptions": {
      "type": "object",
      "properties": {
        "ipaddr": {
          "description": "Ip address",
          "type": "string",
          "readOnly": true
        },
        "vlan": {
          "description": "VLAN name",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "description": "Error code",
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "description": "Error message",
          "type": "string"
        }
      }
    },
    "Exportoptions": {
      "type": "object",
      "properties": {
        "description": {
          "description": "Description",
          "type": "string",
          "readOnly": true
        },
        "private": {
          "description": "Export to private template",
          "type": "boolean",
          "readOnly": true
        },
        "size": {
          "description": "Size",
          "type": "string",
          "enum": [
            "tiny",
            "small",
            "medium",
            "large",
            "huge"
          ]
        },
        "token": {
          "description": "Token",
          "type": "string",
          "readOnly": true
        },
        "version": {
          "description": "Version number",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Fingerprint": {
      "type": "object",
      "required": [
        "hash"
      ],
      "properties": {
        "hash": {
          "description": "fingerprint",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Importoptions": {
      "type": "object",
      "properties": {
        "token": {
          "description": "Token",
          "type": "string",
          "readOnly": true
        },
        "torrent": {
          "description": "Get template using torrent",
          "type": "boolean",
          "readOnly": true
        },
        "version": {
          "description": "Version",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "InfoHostStat": {
      "type": "object",
      "properties": {
        "cpu": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/cpuInfo"
          },
          "readOnly": true
        },
        "disk": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/diskInfo"
          },
          "readOnly": true
        },
        "hostname": {
          "type": "string",
          "readOnly": true
        },
        "quota": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/quotaInfo"
          },
          "readOnly": true
        },
        "ram": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ramInfo"
          },
          "readOnly": true
        }
      }
    },
    "Item": {
      "type": "object",
      "required": [
        "text"
      ],
      "properties": {
        "text": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Message": {
      "type": "object",
      "required": [
        "text"
      ],
      "properties": {
        "exitcode": {
          "description": "Returned Exit code",
          "type": "string",
          "readOnly": true
        },
        "text": {
          "description": "Message returned",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "MetricInfo": {
      "type": "object",
      "properties": {
        "messages": {
          "type": "string",
          "readOnly": true
        },
        "series": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "P2pArgs": {
      "type": "object",
      "required": [
        "interfaceName",
        "hash",
        "key",
        "ttl"
      ],
      "properties": {
        "hash": {
          "description": "Hash",
          "type": "string",
          "readOnly": true
        },
        "interfaceName": {
          "description": "Interface Name",
          "type": "string",
          "readOnly": true
        },
        "key": {
          "description": "Key",
          "type": "string",
          "readOnly": true
        },
        "localPeepIPAddr": {
          "description": "Local Peep IP Address",
          "type": "string",
          "readOnly": true
        },
        "portRange": {
          "description": "Port Range",
          "type": "string",
          "readOnly": true
        },
        "ttl": {
          "description": "Life time",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Promoteoptions": {
      "type": "object",
      "properties": {
        "source": {
          "description": "Source name",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "ProxyArgs": {
      "type": "object",
      "required": [
        "vlan"
      ],
      "properties": {
        "cert": {
          "description": "SSL certificate",
          "type": "string",
          "minLength": 1
        },
        "domain": {
          "description": "Domain name",
          "type": "string",
          "minLength": 1
        },
        "node": {
          "description": "Node Name",
          "type": "string",
          "minLength": 1
        },
        "policy": {
          "type": "string",
          "enum": [
            "rr",
            "lb",
            "hash"
          ]
        },
        "vlan": {
          "description": "VLan Name",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Text": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "cpuInfo": {
      "type": "object",
      "properties": {
        "coreCount": {
          "description": "Number of CPU Cores",
          "type": "string",
          "readOnly": true
        },
        "frequency": {
          "description": "CPU frequency",
          "type": "string",
          "readOnly": true
        },
        "idle": {
          "description": "CPU Idle",
          "type": "string",
          "readOnly": true
        },
        "model": {
          "description": "CPU model",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "diskInfo": {
      "type": "object",
      "properties": {
        "total": {
          "description": "Total space available",
          "type": "string",
          "readOnly": true
        },
        "used": {
          "description": "Used space",
          "type": "string",
          "readOnly": true
        }
      }
    },
    "diskStructInfo": {
      "type": "object",
      "properties": {
        "resource": {
          "description": "Resources available",
          "type": "string",
          "enum": [
            "home",
            "opt",
            "rootfs",
            "var"
          ]
        }
      }
    },
    "quotaArgs": {
      "type": "object",
      "required": [
        "name",
        "resource"
      ],
      "properties": {
        "name": {
          "type": "string",
          "readOnly": true
        },
        "resource": {
          "type": "string",
          "enum": [
            "network",
            "rootfs",
            "home",
            "var",
            "opt",
            "disk",
            "cpuset",
            "ram",
            "cpu"
          ]
        },
        "size": {
          "type": "string",
          "minLength": 1
        },
        "threshold": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "quotaInfo": {
      "type": "object",
      "properties": {
        "container": {
          "type": "string",
          "readOnly": true
        },
        "cpu": {
          "type": "string",
          "readOnly": true
        },
        "disk": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/diskStructInfo"
          },
          "readOnly": true
        },
        "ram": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "quotaOutput": {
      "type": "object",
      "required": [
        "quota",
        "threshold"
      ],
      "properties": {
        "quota": {
          "type": "string",
          "readOnly": true
        },
        "threshold": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "ramInfo": {
      "type": "object",
      "properties": {
        "cached": {
          "type": "string",
          "readOnly": true
        },
        "free": {
          "type": "string",
          "readOnly": true
        },
        "total": {
          "type": "string",
          "readOnly": true
        }
      }
    }
  }
}`))
}
