// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Batchline batchline
// swagger:model Batchline
type Batchline struct {

	// Action to be executed list, backup, import, promote etc.
	// Required: true
	// Read Only: true
	Action string `json:"action"`

	// args
	// Required: true
	Args BatchlineArgs `json:"args"`
}

// Validate validates this batchline
func (m *Batchline) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateArgs(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Batchline) validateAction(formats strfmt.Registry) error {

	if err := validate.RequiredString("action", "body", string(m.Action)); err != nil {
		return err
	}

	return nil
}

func (m *Batchline) validateArgs(formats strfmt.Registry) error {

	if err := validate.Required("args", "body", m.Args); err != nil {
		return err
	}

	if err := m.Args.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Batchline) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Batchline) UnmarshalBinary(b []byte) error {
	var res Batchline
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
