// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CPUInfo cpu info
// swagger:model cpuInfo
type CPUInfo struct {

	// core count
	// Read Only: true
	CoreCount string `json:"coreCount,omitempty"`

	// frequency
	// Read Only: true
	Frequency string `json:"frequency,omitempty"`

	// idle
	// Read Only: true
	IDLE string `json:"idle,omitempty"`

	// model
	// Read Only: true
	Model string `json:"model,omitempty"`
}

// Validate validates this cpu info
func (m *CPUInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CPUInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CPUInfo) UnmarshalBinary(b []byte) error {
	var res CPUInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
