// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DiskStructInfo disk struct info
// swagger:model diskStructInfo
type DiskStructInfo struct {

	// home
	// Read Only: true
	Home string `json:"home,omitempty"`

	// opt
	// Read Only: true
	Opt string `json:"opt,omitempty"`

	// rootfs
	// Read Only: true
	Rootfs string `json:"rootfs,omitempty"`

	// var
	// Read Only: true
	Var string `json:"var,omitempty"`
}

// Validate validates this disk struct info
func (m *DiskStructInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DiskStructInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiskStructInfo) UnmarshalBinary(b []byte) error {
	var res DiskStructInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
