// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ExportOptions export options
// swagger:model exportOptions
type ExportOptions struct {

	// description
	// Read Only: true
	Description string `json:"description,omitempty"`

	// private
	// Read Only: true
	Private *bool `json:"private,omitempty"`

	// size
	// Read Only: true
	Size int64 `json:"size,omitempty"`

	// token
	// Read Only: true
	Token string `json:"token,omitempty"`

	// version
	// Read Only: true
	Version string `json:"version,omitempty"`
}

// Validate validates this export options
func (m *ExportOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ExportOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExportOptions) UnmarshalBinary(b []byte) error {
	var res ExportOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
