// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Importoptions importoptions
// swagger:model Importoptions
type Importoptions struct {

	// Token
	// Read Only: true
	Token string `json:"token,omitempty"`

	// Get template using torrent
	// Read Only: true
	Torrent *bool `json:"torrent,omitempty"`

	// Version
	// Read Only: true
	Version string `json:"version,omitempty"`
}

// Validate validates this importoptions
func (m *Importoptions) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Importoptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Importoptions) UnmarshalBinary(b []byte) error {
	var res Importoptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
