// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InfoHostStat info host stat
// swagger:model InfoHostStat
type InfoHostStat struct {

	// cpu
	CPU InfoHostStatCPU `json:"cpu"`

	// disk
	Disk InfoHostStatDisk `json:"disk"`

	// hostname
	// Read Only: true
	Hostname string `json:"hostname,omitempty"`

	// quota
	Quota InfoHostStatQuota `json:"quota"`

	// ram
	RAM InfoHostStatRAM `json:"ram"`
}

// Validate validates this info host stat
func (m *InfoHostStat) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InfoHostStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InfoHostStat) UnmarshalBinary(b []byte) error {
	var res InfoHostStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
