// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// QuotaInfo quota info
// swagger:model quotaInfo
type QuotaInfo struct {

	// container
	// Read Only: true
	Container string `json:"container,omitempty"`

	// cpu
	// Read Only: true
	CPU string `json:"cpu,omitempty"`

	// disk
	Disk QuotaInfoDisk `json:"disk"`

	// ram
	// Read Only: true
	RAM string `json:"ram,omitempty"`
}

// Validate validates this quota info
func (m *QuotaInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *QuotaInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuotaInfo) UnmarshalBinary(b []byte) error {
	var res QuotaInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
