// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QuotaArgs quota args
// swagger:model quotaArgs
type QuotaArgs struct {

	// name
	// Required: true
	// Read Only: true
	Name string `json:"name"`

	// resource
	// Required: true
	Resource *string `json:"resource"`

	// size
	// Min Length: 1
	Size string `json:"size,omitempty"`

	// threshold
	// Min Length: 1
	Threshold string `json:"threshold,omitempty"`
}

// Validate validates this quota args
func (m *QuotaArgs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResource(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateThreshold(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuotaArgs) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

var quotaArgsTypeResourcePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["network","rootfs","home","var","opt","disk","cpuset","ram","cpu"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		quotaArgsTypeResourcePropEnum = append(quotaArgsTypeResourcePropEnum, v)
	}
}

const (
	// QuotaArgsResourceNetwork captures enum value "network"
	QuotaArgsResourceNetwork string = "network"
	// QuotaArgsResourceRootfs captures enum value "rootfs"
	QuotaArgsResourceRootfs string = "rootfs"
	// QuotaArgsResourceHome captures enum value "home"
	QuotaArgsResourceHome string = "home"
	// QuotaArgsResourceVar captures enum value "var"
	QuotaArgsResourceVar string = "var"
	// QuotaArgsResourceOpt captures enum value "opt"
	QuotaArgsResourceOpt string = "opt"
	// QuotaArgsResourceDisk captures enum value "disk"
	QuotaArgsResourceDisk string = "disk"
	// QuotaArgsResourceCpuset captures enum value "cpuset"
	QuotaArgsResourceCpuset string = "cpuset"
	// QuotaArgsResourceRAM captures enum value "ram"
	QuotaArgsResourceRAM string = "ram"
	// QuotaArgsResourceCPU captures enum value "cpu"
	QuotaArgsResourceCPU string = "cpu"
)

// prop value enum
func (m *QuotaArgs) validateResourceEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, quotaArgsTypeResourcePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *QuotaArgs) validateResource(formats strfmt.Registry) error {

	if err := validate.Required("resource", "body", m.Resource); err != nil {
		return err
	}

	// value enum
	if err := m.validateResourceEnum("resource", "body", *m.Resource); err != nil {
		return err
	}

	return nil
}

func (m *QuotaArgs) validateSize(formats strfmt.Registry) error {

	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := validate.MinLength("size", "body", string(m.Size), 1); err != nil {
		return err
	}

	return nil
}

func (m *QuotaArgs) validateThreshold(formats strfmt.Registry) error {

	if swag.IsZero(m.Threshold) { // not required
		return nil
	}

	if err := validate.MinLength("threshold", "body", string(m.Threshold), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QuotaArgs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuotaArgs) UnmarshalBinary(b []byte) error {
	var res QuotaArgs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
