// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/subutai-io/agent/rest/models"
)

// DestroyEntryNoContentCode is the HTTP code returned for type DestroyEntryNoContent
const DestroyEntryNoContentCode int = 204

/*DestroyEntryNoContent Deleted

swagger:response destroyEntryNoContent
*/
type DestroyEntryNoContent struct {
}

// NewDestroyEntryNoContent creates DestroyEntryNoContent with default headers values
func NewDestroyEntryNoContent() *DestroyEntryNoContent {
	return &DestroyEntryNoContent{}
}

// WriteResponse to the client
func (o *DestroyEntryNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DestroyEntryDefault error

swagger:response destroyEntryDefault
*/
type DestroyEntryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDestroyEntryDefault creates DestroyEntryDefault with default headers values
func NewDestroyEntryDefault(code int) *DestroyEntryDefault {
	if code <= 0 {
		code = 500
	}

	return &DestroyEntryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the destroy entry default response
func (o *DestroyEntryDefault) WithStatusCode(code int) *DestroyEntryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the destroy entry default response
func (o *DestroyEntryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the destroy entry default response
func (o *DestroyEntryDefault) WithPayload(payload *models.Error) *DestroyEntryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the destroy entry default response
func (o *DestroyEntryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DestroyEntryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
