---
swagger: '2.0'
info:
  description: |
    API to handle agent
  version: 0.0.1
  title: Agent API
host: 'localhost:8080'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /agent/rest/list:
    get:
      tags: 
        - agent 
        - cli 
        - list
      operationId: cliList
      description: "Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc."
      parameters: 
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
        - name: containersOnly
          in: query
          type: boolean
        - name: templatesOnly
          in: query
          type: boolean
        - name: detailedInfo
          in: query
          type: boolean
        - name: withAncestors
          in: query
          type: boolean
        - name: withParents
          in: query
          type: boolean
      responses:
        '200':
          description: List all subutai instances
          schema:
            type: array
            items:
              $ref: "#/definitions/container"
        default:
          description: generic error response
          schema:
      x-swagger-router-controller: Default
  /agent/container/{name}:
    parameters:
      - type: string
        name: name
        in: path
        required: true
      - name: containersOnly
        in: query
        type: boolean
      - name: templatesOnly
        in: query
        type: boolean
      - name: detailedInfo
        in: query
        type: boolean
      - name: withAncestors
        in: query
        type: boolean
      - name: withParents
        in: query
        type: boolean
    get:
      tags:
        - agent
        - cli 
        - container
      operationId: getContainerInfo
      description: "Get container Info in JSON formatted object"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/container"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - container
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  container:
    type: object
    required:
      - description
    properties:
      name:
        type: string
        readOnly: true
      description:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
