---
swagger: '2.0'
info:
  description: |
    API to handle agent
  version: 0.0.1
  title: Agent API
host: 'localhost:8080'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /agent/rest/list:
    get:
      operationId: cli.LxcList
      description: "Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc."
      parameters: []
      responses:
        '200':
          description: Get all subutai instances
      x-swagger-router-controller: Default
definitions:
  List:
    type: object
    properties:
      text:
        type: string
