---
swagger: '2.0'
info:
  description: |
    API to handle agent
  version: 0.0.1
  title: Agent API
host: 'localhost:8080'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /agent/rest/list:
    get:
      tags: agent cli list
      operationId: cliList
      description: "Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc."
      parameters: 
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        '200':
          description: GeList all subutai instances
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
      x-swagger-router-controller: Default
definitions:
  container:
    type: object
    properties:
      text:
        type: string

  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
