---
swagger: '2.0'
info:
  description: |
    API to handle agent
  version: 0.0.1
  title: Agent API
host: 'localhost:8080'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rest/v1/rh/id:
    get:
      tags: 
        - agent 
        - rh
      operationId: rhID
      description: "Returns JSON formatted Id of RH, UUID which is the PGP fingerprint"
      responses:
        '200':
          description: JSON formatted Id of RH
          schema:
            type: array
            items:
              $ref: "#/definitions/fingerprint"
        default:
          description: generic error response
          schema:
      x-swagger-router-controller: Default
  /rest/v1/list:
    get:
      tags: 
        - agent 
        - cli 
        - list
      operationId: cliList
      description: "Info returns JSON formatted list of Subutai instances with information such as IP address, parent template, etc."
      parameters: 
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
        - name: containersOnly
          in: query
          type: boolean
        - name: templatesOnly
          in: query
          type: boolean
        - name: withAncestors
          in: query
          type: boolean
        - name: withParents
          in: query
          type: boolean
      responses:
        '200':
          description: List all subutai instances
          schema:
            type: array
            items:
              $ref: "#/definitions/container"
        default:
          description: generic error response
          schema:
      x-swagger-router-controller: Default
  /rest/v1/container/{name}:
    parameters:
      - type: string
        name: name
        in: path
        required: true
      - name: containersOnly
        in: query
        type: boolean
      - name: templatesOnly
        in: query
        type: boolean
      - name: detailedInfo
        in: query
        type: boolean
      - name: withAncestors
        in: query
        type: boolean
      - name: withParents
        in: query
        type: boolean
    get:
      tags:
        - agent
        - cli 
        - container
      operationId: getContainerInfo
      description: "Get container Info in JSON formatted object"

      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/container"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - container
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /rest/v1/backup/{name}:
    parameters:
      - type: string
        name: name
        in: path
        required: true
      - name: full
        in: query
        type: boolean
      - name: stop
        in: query
        type: boolean
    get:
      tags:
        - agent
        - cli 
        - container
      operationId: backupContainer
      description: "BackupContainer takes a snapshots of each container's volume and stores it in the `/mnt/backups/container_name/datetime/` directory.
A full backup creates a delta-file of each BTRFS subvolume. An incremental backup (default) creates a delta-file with the difference of changes between the current and last snapshots.
All deltas are compressed to archives in `/mnt/backups/` directory (container_datetime.tar.gz or container_datetime_Full.tar.gz for full backup).
A changelog file can be found next to backups archive (container_datetime_changelog.txt or container_datetime_Full_changelog.txt) which contains a list of changes made between two backups."
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/message"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  container:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        readOnly: true
      parent:
        type: string
        minLength: 1
      ancestor:
        type: string
        minLength: 1
  fingerprint:
    type: object
    required:
      - hash
    properties:
      hash:
        type: string
        readOnly: true
  message:
    type: object
    required:
      - text
    properties:
      text:
        type: string
        readOnly: true
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
